version: '3.9'  # Phiên bản Docker Compose

services:
  nextjs-app:
    build: .  # Sử dụng Dockerfile ở thư mục hiện tại
    ports:
      - "3000:3000"  # Mapping port trên host và container
    volumes:
      - .:/app # Mount code nguồn để development
      # Thêm dòng dưới nếu bạn muốn sử dụng tên khối lượng được persist dữ liệu sau khi container bị dừng
      #- nextjs-data:/app/.next 

volumes:
  # Tạo named volume để persist dữ liệu
  # nextjs-data: